import {BLOOM,MODALITIES,escapeHTML as esc,readCourse,parseOutline,safeText,inferLevel,outcomeIssues,wordCount,providedOutcomes} from './core.js';
import * as ai from './ai.js';
import {reportBlocks,blocksHTML,blocksText,exportDocx,exportHtml} from './exports.js';
const $=id=>document.getElementById(id);
const state={course:null,outcomes:[],assignments:[],reviewed:false,settings:{modalities:['Read/write'],knowledge:'Conceptual',duration:'60–90 minutes',count:1,resilient:false},step:'course',goal:'assignments',sloMode:'provided',sloInput:''};
let busy=false,dirty=false,importWorker=null,pdfTask=null,importEpoch=0;
const options=(items,selected)=>items.map(x=>`<option${x===selected?' selected':''}>${esc(x)}</option>`).join('');
function notice(text,error=false){$('notice').className=error?'error':'';$('notice').textContent=text;}
function confirmAction(message){return new Promise(resolve=>{const d=document.createElement('dialog');d.innerHTML=`<h2>Confirm workspace change</h2><p>${esc(message)}</p><form method="dialog"><div class="toolbar"><button class="button secondary" value="cancel">Keep working</button><button class="button primary" value="confirm">Continue</button></div></form>`;d.addEventListener('close',()=>{const yes=d.returnValue==='confirm';d.remove();resolve(yes);},{once:true});document.body.append(d);d.showModal();});}
function progress(text){$('notice').className='';$('notice').replaceChildren(document.createTextNode(text+' '));const b=document.createElement('button');b.className='button secondary';b.textContent='Cancel';b.onclick=()=>{ai.stop();notice('AI stopped. Your existing work is unchanged.');};$('notice').append(b);}
function setBusy(value){busy=value;document.querySelectorAll('main button,main input,main textarea,main select,.step').forEach(el=>{if(!el.closest('#notice'))el.disabled=value;});$('workspace').setAttribute('aria-busy',String(value));}
async function action(fn){try{await fn();}catch(e){notice(e.message||'Something went wrong. Your existing work is unchanged.',true);}}
async function aiAction(fn){if(busy)return;setBusy(true);try{await fn();}catch(e){notice(e.message||'Local AI could not complete this request. Try loading the model again.',true);}finally{setBusy(false);}}
function heading(n,title,subtitle){return `<div class="page-heading"><div><p class="eyebrow">0${n===4&&state.goal==='slos'?3:n} / ${['','COURSE OUTLINE','LEARNING OUTCOMES','ASSIGNMENTS','REVIEW & EXPORT'][n]}</p><h1>${title}</h1><p class="lede">${subtitle}</p></div></div>`;}
function aiBox(){return `<div class="card ai-box"><div><span class="chip">FREE · RUNS ON YOUR DEVICE</span><h2>AI for your course, privately.</h2><p class="small muted">Qwen2.5 1.5B runs locally through WebLLM. Initial download is approximately 1 GB; about 2 GB of available GPU memory is recommended. A compatible WebGPU browser is required. Model files may remain cached; course text and drafts are never saved by the app. The model host receives download requests, not course text.</p></div><div class="toolbar"><button class="button secondary" data-action="load-ai">${ai.ready()?'AI is ready':'Load free AI model'}</button><button class="text-button" data-action="remove-model">Remove cached model</button></div></div>`;}
function saveCourse(){
  const next=readCourse(Object.fromEntries(['title','description','objectives','existing'].map(k=>[k,$(k).value])));
  if(JSON.stringify(next)!==JSON.stringify(state.course)){
    const importedChanged=next.existing.join('\n')!==(state.course?.existing||[]).join('\n');
    state.course=next;state.assignments=[];state.reviewed=false;state.assignmentSloIndices=[];state.assignmentObjectiveIds=[];
    if(importedChanged){state.outcomes=[];state.sloInput=next.existing.join('\n');state.sloMode=state.sloInput?'provided':null;}
    else if(state.outcomes.length)state.outcomes=providedOutcomes(state.outcomes.map(o=>o.sentence).join('\n'));
  }dirty=true;
}
function show(step){if(busy)return;if(state.goal==='slos'&&step==='assignments')step='report';if(!['welcome','course'].includes(step)&&!state.course){notice('Add your course information first.',true);return;}if(['assignments','report'].includes(step)&&!state.outcomes.length){notice('Add or generate learning outcomes first.',true);return;}if(step==='report')state.assignments.forEach(a=>safeText(a.notes||'',3000));notice('');state.step=step;$('clear').hidden=step==='welcome';document.querySelectorAll('.panel').forEach(p=>p.hidden=p.id!==step+'-panel');document.querySelectorAll('.step').forEach(b=>{b.classList.toggle('active',b.dataset.step===step);b.setAttribute('aria-current',b.dataset.step===step?'step':'false');});if(step==='outcomes'){if(state.goal==='assignments')state.sloMode='provided';renderOutcomes();}if(step==='assignments')renderAssignments();if(step==='report')renderReport();$('workspace').focus();window.scrollTo(0,0);}
function sourceChecks(ids,i){return state.course.objectives.map((o,j)=>`<label class="objective-option"><input type="checkbox" data-field="objectiveIds" value="${j+1}"${ids.includes(j+1)?' checked':''}><span><strong>Objective ${j+1}</strong> ${esc(o)}</span></label>`).join('');}
function crosswalk(){
  const covered=new Set(state.outcomes.flatMap(o=>o.objectiveIds));const missing=state.course.objectives.map((_,i)=>i+1).filter(i=>!covered.has(i));
  return `<h2 class="section-heading">Your alignment crosswalk</h2><div class="card"><div class="table-scroll"><table><thead><tr><th>SLO</th><th>Aligned course objectives</th><th>Bloom’s level</th></tr></thead><tbody>${state.outcomes.map((o,i)=>`<tr><td><strong>SLO ${i+1}</strong><br>${esc(o.sentence)}</td><td>${o.objectiveIds.length?o.objectiveIds.map(id=>`<div>${id}. ${esc(state.course.objectives[id-1])}</div>`).join(''):'No confirmed links'}</td><td>${esc(o.level)}${['pending','stale'].includes(o.alignmentStatus)?'<br><span class="small">Alignment needs review</span>':''}</td></tr>`).join('')}</tbody></table></div><p class="small muted">Each SLO maps to all course objectives it meaningfully supports, alongside its Bloom’s level. Multiple objectives can support one SLO, and an objective can connect to several SLOs; review each suggested link for course fit.</p>${missing.length?`<p class="coverage">Coverage to review: objective(s) ${missing.join(', ')} are not yet mapped.</p>`:''}</div>`;
}
function renderOutcomes(){
  const provided=state.sloMode==='provided',create=state.sloMode==='create';
  $('outcomes-panel').innerHTML=heading(2,state.goal==='assignments'?'Which SLOs should the assignments measure?':'Add or create your learning outcomes.',state.goal==='assignments'?'Add existing SLOs. The wizard aligns them, then moves you to assignment options.':'Your course is ready. Choose how to develop SLOs; the wizard aligns them to objectives and Bloom’s taxonomy.')+
  `<div class="slo-choices"${state.goal==='assignments'?' hidden':''} role="group" aria-label="Choose how to add SLOs"><button class="choice-card${provided?' selected':''}" aria-pressed="${provided}" data-action="choose-provided"><span class="choice-icon" aria-hidden="true">＋</span><strong>Add existing SLOs</strong><span>Paste your outcomes. Keep the wording and automatically identify their alignments.</span></button><button class="choice-card${create?' selected':''}" aria-pressed="${create}" data-action="choose-create"><span class="choice-icon" aria-hidden="true">✦</span><strong>Create SLOs with AI</strong><span>Create one outcome, review it, then add another. Objective links and Bloom’s level are automatic.</span></button></div>`+
  (provided?`<section class="card section-heading"><h2>Add your SLOs</h2><label for="provided-slos">Student learning outcomes <span class="required">one per line · up to 12 total</span></label><textarea id="provided-slos" rows="5" maxlength="8000" placeholder="Analyze environmental data using relevant evidence.&#10;Evaluate sustainable resource strategies against stated criteria.">${esc(state.sloInput)}</textarea><p class="small muted">Your wording stays intact. The wizard considers every course objective and identifies the appropriate Bloom’s level. Unclear or unsupported links are flagged for review.</p><button class="button primary" data-action="add-provided">${state.goal==='assignments'?'Use these SLOs for assignments →':'Add SLOs & align automatically →'}</button></section>`:'')+
  (create?`<section class="card section-heading"><h2>Create one SLO at a time.</h2><p class="muted">Review each outcome before adding another. Your existing SLOs stay in place.</p><div class="toolbar">${state.outcomes.length<12?`<button class="button primary" data-action="draft-one">${state.outcomes.length?'Add another SLO':'Create one SLO'} →</button>`:'<p>You have 12 SLOs. Edit or remove an outcome before adding another.</p>'}</div><p class="small muted">The wizard automatically selects objective links and Bloom’s level. Free local AI · no paid service.</p></section>`:'')+
  (state.sloMode?`<p class="small muted">Adding, aligning, or creating SLOs uses local AI and loads the model if needed. Review the device and download requirements below.</p>`:'')+
  (state.outcomes.length?`<div class="toolbar"><h2>Your SLOs <span class="chip">${state.outcomes.length}</span></h2><button class="button secondary" data-action="align-all">Realign all SLOs automatically</button></div>`:'')+
  `<div id="outcome-list">${state.outcomes.map((o,i)=>outcomeCard(o,i)).join('')}</div><div id="crosswalk">${state.outcomes.length?crosswalk():''}</div>`+
  `<details class="ai-details"><summary>Local AI · device requirements & model controls</summary>${aiBox()}</details>`+
  `<div class="toolbar"><button class="button secondary" data-action="back-course">Back to course</button><button class="button primary" data-action="to-assignments">${state.goal==='slos'?'Review & export SLOs →':'Continue to assignments →'}</button></div>`;
}
function alignmentSummary(o){return `<span class="chip">Bloom’s level: ${esc(o.level)}</span>${o.objectiveIds.map(id=>`<span class="chip">Objective ${id}</span>`).join('')||'<span class="muted small">Objective alignment pending</span>'}`;}
function outcomeCard(o,i){
  const issues=outcomeIssues(o),status=o.alignmentStatus==='complete'?'Selected by the wizard':o.alignmentStatus==='manual'?'Your override applied':o.alignmentStatus==='stale'?'Realignment needed':'Alignment pending';
  return `<article class="card outcome" data-outcome="${i}"><div class="outcome-title"><h3>SLO ${i+1}</h3><span class="small muted" id="alignment-status-${i}">${status}</span><button class="text-button danger" data-action="delete-outcome" data-index="${i}">Remove</button></div><label for="slo-${i}">Outcome sentence</label><textarea id="slo-${i}" data-field="sentence" rows="2" maxlength="500">${esc(o.sentence)}</textarea><div class="badge-line" id="alignment-summary-${i}">${alignmentSummary(o)}</div><div class="alignment-explanation" id="alignment-explanation-${i}">${o.alignmentRationale?esc(o.alignmentRationale):'The wizard will select the relevant objectives and Bloom’s level automatically.'}</div><details class="alignment-override"><summary>Adjust alignment <span class="small muted">optional</span></summary><p class="small muted">Override the wizard’s selections only if needed. Changes apply immediately.</p><label for="level-${i}">Bloom’s level</label><select id="level-${i}" data-field="level">${options(['Needs review',...Object.keys(BLOOM)],o.level)}</select><fieldset class="objective-links"><legend>Course objectives <span class="required">select all that apply</span></legend>${sourceChecks(o.objectiveIds,i)}</fieldset><button class="text-button" data-action="align-one" data-index="${i}">Restore automatic alignment</button></details><p class="checks${issues.length?' warning':''}" id="checks-${i}">${issues.length?esc(issues.join(' ')):`${wordCount(o.sentence)} words · Review the suggested alignment.`}</p><button class="button secondary" data-action="rewrite-one" data-index="${i}">Rewrite SLO with AI</button>${['pending','stale'].includes(o.alignmentStatus)?` <button class="button secondary" data-action="align-one" data-index="${i}">Retry automatic alignment</button>`:''}</article>`;
}
function updateOutcome(target){
  const card=target.closest('[data-outcome]');if(!card||!target.dataset.field)return;const i=Number(card.dataset.outcome),field=target.dataset.field,o=state.outcomes[i];
  const value=field==='objectiveIds'?[...card.querySelectorAll('[data-field=objectiveIds]:checked')].map(el=>Number(el.value)):target.value;
  if(JSON.stringify(o[field])===JSON.stringify(value))return;
  o[field]=value;
  if(field==='sentence'){o.alignmentStatus='stale';o.alignmentRationale='The wizard will refresh alignment when you finish editing.';}
  else if(['level','objectiveIds'].includes(field)){o.alignmentStatus='manual';o.alignmentRationale='Faculty override applied. Use “Restore automatic alignment” to ask the wizard to select again.';}
  $('alignment-status-'+i).textContent=o.alignmentStatus==='manual'?'Your override applied':'Realignment needed';
  $('alignment-explanation-'+i).textContent=o.alignmentRationale;
  $('alignment-summary-'+i).innerHTML=alignmentSummary(o);
  state.assignments=[];state.reviewed=false;dirty=true;
  const issues=outcomeIssues(o);$('checks-'+i).textContent=issues.length?issues.join(' '):`${wordCount(o.sentence)} words · Review the suggested alignment.`;$('checks-'+i).className='checks'+(issues.length?' warning':'');$('crosswalk').innerHTML=crosswalk();
}
function requireOutcomes(){if(!state.outcomes.length)throw new Error('Add or generate at least one SLO.');state.outcomes.forEach((o,i)=>{safeText(o.sentence,500);const issues=outcomeIssues(o);if(issues.length)throw new Error(`Review SLO ${i+1}: ${issues.join(' ')}`);});}
function assignmentTargets(){
  const selected=state.assignmentSloIndices||[],ids=state.assignmentObjectiveIds||[];
  const checks=(items,name,chosen,base)=>items.map((text,j)=>'<label class="objective-option"><input type="checkbox" name="'+name+'" value="'+(j+base)+'"'+(chosen.includes(j+base)?' checked':'')+'><span>'+esc((base?'Objective ':'SLO ')+(j+1)+': '+text)+'</span></label>').join('');
  return '<div class="card"><fieldset class="objective-links"><legend>SLOs for this assignment</legend>'+checks(state.outcomes.map(o=>o.sentence),'assignment-slo',selected,0)+'</fieldset><fieldset class="objective-links"><legend>Course objectives for this assignment</legend>'+checks(state.course.objectives,'assignment-objective',ids,1)+'</fieldset><p class="small muted">Choose at least one SLO and one objective. You can select several.</p></div>';
}
function useAssignmentSlos(){
  const next=providedOutcomes($('existing').value);
  if(JSON.stringify(next.map(o=>o.sentence))!==JSON.stringify(state.outcomes.map(o=>o.sentence))){state.outcomes=next;state.assignments=[];state.assignmentSloIndices=[];state.assignmentObjectiveIds=[];state.reviewed=false;}
  state.sloInput='';dirty=true;show('assignments');
}
function renderAssignments(){const s=state.settings;$('assignments-panel').innerHTML=heading(3,'Create an assignment.','Select the SLOs, objectives, and VARK elements for one learning assignment.')+assignmentTargets()+`<div class="card section-heading"><div class="controls-grid"><div><h2>VARK elements</h2><p class="small muted">Select one or more: Visual, Aural, Read/write, or Kinesthetic. These describe activity formats, not fixed student types.</p><div class="modality-grid">${Object.entries(MODALITIES).map(([k,v])=>`<label class="modality"><input type="checkbox" name="modality" value="${esc(k)}"${s.modalities.includes(k)?' checked':''}><span><strong>${esc(k)}</strong><small>${esc(v)}</small></span></label>`).join('')}</div><label class="toggle"><input id="resilient" type="checkbox"${s.resilient?' checked':''}><span><strong>Make assignments AI-resilient</strong><span class="small muted"> · Add process checkpoints, course-specific evidence, and individual explanation. No AI detectors.</span></span></label></div><div><label for="knowledge">Knowledge dimension</label><select id="knowledge">${options(['Factual','Conceptual','Procedural','Metacognitive'],s.knowledge)}</select><div class="field-grid"><div><label for="duration">Time per activity</label><select id="duration">${options(['30–45 minutes','60–90 minutes','1 week','2 weeks'],s.duration)}</select></div><div><p class="small muted">One assignment is created per click. You can add another after reviewing it.</p></div></div><p class="small muted">Each assignment includes instructions, a direct assessment rubric, accessible alternatives, and an explanation of alignment.</p></div></div><div class="card-actions"><span class="small muted">Faculty review is essential, especially for specialist subjects.</span><button class="button primary" data-action="generate-assignments">${state.assignments.length?'Add another assignment':'Create assignment'}</button></div></div><details class="ai-details"><summary>Local AI · device requirements</summary>${aiBox()}</details><div id="assignment-list">${state.assignments.map((a,i)=>assignmentCard(a,i)).join('')}</div><div class="toolbar"><button class="button secondary" data-action="back-course">Back to course</button><button class="button primary" data-action="to-report">Review & export →</button></div>`;}
function assignmentCard(a,i){return `<article class="card assignment"><div class="badge-line">${(a.sloIndices||[a.sloIndex]).map(i=>`<span class="chip">SLO ${i+1}</span>`).join('')}${(a.objectiveIds||[]).map(id=>`<span class="chip">Objective ${id}</span>`).join('')}<span class="chip">${esc(a.settings.modalities.join(' · '))}</span>${a.settings.resilient?'<span class="chip">AI-resilient</span>':''}</div><h3>${esc(a.title)}</h3><p>${esc(a.context)}</p><p><strong>Materials:</strong> ${esc(a.materials)}</p><ol>${a.steps.map(s=>`<li>${esc(s)}</li>`).join('')}</ol><p><strong>Submit:</strong> ${esc(a.artifact)}</p><div class="intro-note"><strong>Why this measures the SLO</strong><br>${esc(a.alignment)}</div><p><strong>Accessible alternatives:</strong> ${esc(a.accessibility)}</p><details><summary>Assessment rubric · 12 points</summary><p class="small muted">0 = no evidence; 1 = emerging; 2 = developing; 3 = meets; 4 = exceeds. Suggested mastery: 9/12, with no criterion below 2. Adjust to course expectations.</p><div class="table-scroll"><table><thead><tr><th>Criterion</th><th>Developing · 2</th><th>Meets · 3</th><th>Exceeds · 4</th></tr></thead><tbody>${a.rubric.map(r=>`<tr><td>${esc(r.name)}</td><td>${esc(r.developing)}</td><td>${esc(r.meets)}</td><td>${esc(r.exceeds)}</td></tr>`).join('')}</tbody></table></div></details>${a.settings.resilient?'<details><summary>AI-resilient evidence plan</summary><p>Collect a planning checkpoint, dated process log, and final artifact. Provide a course-specific case or dataset. Ask for an individual explanation in an accessible equivalent format and disclosure of permitted AI use. Assess demonstrated learning; do not infer misconduct from detector scores.</p></details>':''}<label for="notes-${i}">Faculty adaptations <span class="required">included in exports</span></label><textarea id="notes-${i}" data-notes="${i}" rows="2" maxlength="3000" placeholder="Adjust instructions, scoring, timing, or local materials…">${esc(a.notes||'')}</textarea><button class="text-button" data-action="edit-assignment" data-index="${i}">Edit assignment text</button></article>`;}
function renderReport(){$('report-panel').innerHTML=heading(4,state.goal==='slos'?'Your SLOs, ready to use.':'Your assignments, ready to review.','Review your generated content, then copy or export it.')+`<div class="toolbar"><button class="button secondary" data-action="back-results">← Back to editing</button><button class="button primary" data-action="copy">Copy report</button><button class="button secondary" data-action="pdf">Save PDF</button><button class="button secondary" data-action="docx">Download Word (.docx)</button><button class="button secondary" data-action="html">Download HTML</button></div><label class="review-box no-print"><input id="reviewed" type="checkbox"${state.reviewed?' checked':''}>I reviewed course fit, one-term scope, objective coverage, assessment criteria, and accessibility.</label><p class="small muted no-print">PDF opens your browser’s print dialog; select “Save as PDF.” Word and HTML files download directly. Files you export remain on your device.</p><article class="card report" id="report-content">${blocksHTML(reportBlocks(state))}</article>`;}
async function ensureAI(){if(!ai.ready()){progress('Loading local AI for automatic alignment…');await ai.load(progress);}}
async function generateOne(){await aiAction(async()=>{
  if(state.outcomes.length>=12)throw new Error('Use up to 12 SLOs total. Remove an outcome before adding another.');
  await ensureAI();
  const draft=await ai.draftOutcome(state.course,null,state.outcomes,state.outcomes.length+1,p=>progress(`Creating one SLO · ${p}`));
  state.outcomes.push(draft);state.reviewed=false;dirty=true;renderOutcomes();notice('One SLO created and aligned. Review it, then add another or export.');
});}
async function alignSet(indices){
  await ensureAI();const drafts=[...state.outcomes];
  for(const [n,i]of indices.entries())drafts[i]=await ai.alignOutcome(state.course,state.outcomes[i].sentence,p=>progress(`Aligning SLO ${n+1}/${indices.length} · ${p}`));
  state.outcomes=drafts;state.assignments=[];state.reviewed=false;dirty=true;renderOutcomes();notice('SLO wording preserved. Objective links and Bloom’s levels have been selected automatically. Override them only if needed.');
}
async function addProvided(){
  const added=providedOutcomes($('provided-slos').value);if(added.length+state.outcomes.length>12)throw new Error('Use up to 12 SLOs total. Remove an outcome before adding more.');
  const start=state.outcomes.length;state.outcomes.push(...added);state.sloInput='';state.assignments=[];state.reviewed=false;dirty=true;renderOutcomes();
  await aiAction(()=>alignSet(added.map((_,i)=>start+i)));
  if(state.goal==='assignments'&&state.outcomes.every(o=>o.alignmentStatus==='complete'&&!outcomeIssues(o).length))show('assignments');
}
async function generateAssignments(){await aiAction(async()=>{
  const indices=[...document.querySelectorAll('[name=assignment-slo]:checked')].map(el=>Number(el.value));
  if(!indices.length)throw new Error('Select at least one SLO for the assignment.');
  const selected=indices.map(i=>state.outcomes[i]);
  const ids=[...document.querySelectorAll('[name=assignment-objective]:checked')].map(el=>Number(el.value));
  if(!ids.length)throw new Error('Select at least one course objective.');
  const s={modalities:[...document.querySelectorAll('[name=modality]:checked')].map(x=>x.value),knowledge:$('knowledge').value,duration:$('duration').value,count:1,resilient:$('resilient').checked};
  if(!s.modalities.length)throw new Error('Select at least one activity modality.');
  selected.forEach(o=>safeText(o.sentence,500));
  await ensureAI();
  const a=await ai.draftAssignment(state.course,selected.map((o,j)=>({...o,id:indices[j]+1,objectiveIds:ids})),s,state.assignments.length%3,p=>progress('Creating assignment · '+p));
  state.settings=s;state.assignmentSloIndices=indices;state.assignmentObjectiveIds=ids;
  state.assignments.push({...a,sloIndex:indices[0],sloIndices:[...indices],objectiveIds:[...ids],settings:structuredClone(s),notes:''});state.reviewed=false;dirty=true;
  renderAssignments();notice('Assignment created for SLO(s) '+indices.map(i=>i+1).join(', ')+'. Review it, export it, or create another.');
});}
async function importFile(file){
  if(!file)return;const token=++importEpoch;importWorker?.terminate();await pdfTask?.destroy();pdfTask=null;
  if(file.size>5*1024*1024)throw new Error('Choose a file no larger than 5 MB.');const extension=file.name.split('.').pop().toLowerCase();if(!['txt','pdf','docx'].includes(extension))throw new Error('Use a TXT, DOCX, or text-based PDF file.');
  $('import-status').textContent='Reading document text on your device…';const buffer=await file.arrayBuffer();let text;
  if(extension==='pdf'){
    if(new TextDecoder().decode(buffer.slice(0,5))!=='%PDF-')throw new Error('This file is not a valid PDF.');
    // Conservative preflight for active PDF features. Compressed content is never executed by the text-only reader.
    if(/\/(JavaScript|JS|Launch|EmbeddedFile|RichMedia|XFA|OpenAction)\b/.test(new TextDecoder('latin1').decode(buffer)))throw new Error('PDFs with active or embedded content are not accepted. Export a plain text copy.');
    const pdf=await import('../vendor/pdf.mjs');pdf.GlobalWorkerOptions.workerSrc=new URL('../vendor/pdf.worker.mjs',import.meta.url).href;
    const task=pdf.getDocument({data:new Uint8Array(buffer),isEvalSupported:false,useSystemFonts:false,disableFontFace:true,stopAtErrors:true});pdfTask=task;
    let timer;try{text=await Promise.race([(async()=>{const doc=await task.promise;if(doc.numPages>60)throw new Error('Use a PDF with no more than 60 pages.');let t='';for(let n=1;n<=doc.numPages;n++){const page=await doc.getPage(n),content=await page.getTextContent();t+=content.items.map(x=>x.str+(x.hasEOL?'\n':' ')).join('')+'\n';if(t.length>40000)throw new Error('This outline exceeds 40,000 characters. Import a shorter extract.');page.cleanup();}return t;})(),new Promise((_,reject)=>{timer=setTimeout(()=>reject(new Error('PDF reading timed out. Paste a shorter text extract.')),20000);})]);}finally{clearTimeout(timer);await task.destroy();pdfTask=null;}
  }else{
    text=await new Promise((resolve,reject)=>{const w=new Worker(new URL('./import-worker.js',import.meta.url),{type:'module'});importWorker=w;const timer=setTimeout(()=>{w.terminate();reject(new Error('Document reading timed out. Paste a text extract.'));},12000);const finish=()=>{clearTimeout(timer);w.terminate();if(importWorker===w)importWorker=null;};w.onerror=()=>{finish();reject(new Error('The document could not be read safely. Paste its text instead.'));};w.onmessage=({data})=>{finish();try{if(data.error)throw new Error(data.error);if(data.xml){const doc=new DOMParser().parseFromString(data.xml,'application/xml');if(doc.querySelector('parsererror'))throw new Error('The document XML is malformed.');const NS='http://schemas.openxmlformats.org/wordprocessingml/2006/main';resolve([...doc.getElementsByTagNameNS(NS,'p')].map(p=>[...p.getElementsByTagNameNS(NS,'t')].map(x=>x.textContent).join('')).join('\n'));}else resolve(data.text);}catch(e){reject(e);}};w.postMessage({buffer,extension},[buffer]);});
  }
  if(token!==importEpoch)return;text=safeText(text);if(!text)throw new Error('No readable text was found. Paste the text or use a text-based document.');$('raw').value=text;$('raw').closest('details').open=true;applyParsed(text);$('import-status').textContent='Text extracted locally. Review the fields and source text.';
}
function applyParsed(text){const parsed=parseOutline(text);if(!parsed.detected){notice('Text extracted, but headings were not recognized. Copy the relevant sections from the outline text into the fields.',true);return;}for(const [k,v]of Object.entries(parsed.fields))if(v){if(v.length>$(k).maxLength)throw new Error(`The extracted ${k} section is too long. Review it in the outline text and paste a shorter section.`);$(k).value=v;}dirty=true;notice('Recognized headings were copied into the fields. Check the extracted content, especially where the source uses other section headings.');}
function editAssignment(i){const a=state.assignments[i];const d=document.createElement('dialog');d.innerHTML=`<h2>Edit assignment</h2><form method="dialog"><div>${['title','context','materials','artifact','alignment','accessibility'].map(k=>`<label>${k[0].toUpperCase()+k.slice(1)}<textarea name="${k}" maxlength="1400" rows="2">${esc(a[k])}</textarea></label>`).join('')}<label>Student steps · one per line<textarea name="steps" rows="6" maxlength="5000">${esc(a.steps.join('\n'))}</textarea></label>${a.rubric.map((r,j)=>`<h3>Rubric criterion ${j+1}</h3>${['name','developing','meets','exceeds'].map(k=>`<label>${k}<textarea name="rubric-${j}-${k}" maxlength="700" rows="2">${esc(r[k])}</textarea></label>`).join('')}`).join('')}</div><p id="edit-error" role="alert"></p><div class="toolbar"><button type="button" class="button primary" id="save-edit">Save edits</button><button class="button secondary">Cancel</button></div></form>`;document.body.append(d);d.addEventListener('close',()=>d.remove());d.querySelector('#save-edit').onclick=()=>{try{const data=new FormData(d.querySelector('form')),next={...a};for(const k of ['title','context','materials','artifact','alignment','accessibility'])next[k]=safeText(data.get(k),1400);if(['title','context','materials','artifact','alignment','accessibility'].some(k=>!next[k]))throw new Error('Keep all assignment fields filled.');next.steps=safeText(data.get('steps'),5000).split('\n').map(x=>x.trim()).filter(Boolean);if(!next.steps.length)throw new Error('Add at least one step.');next.rubric=a.rubric.map((r,j)=>Object.fromEntries(['name','developing','meets','exceeds'].map(k=>{const v=safeText(data.get(`rubric-${j}-${k}`),700);if(!v)throw new Error('Complete each rubric descriptor.');return[k,v];})));state.assignments[i]=next;state.reviewed=false;dirty=true;d.close();renderAssignments();}catch(e){d.querySelector('#edit-error').textContent=e.message;}};d.showModal();}
const actions={
  'load-ai':()=>aiAction(async()=>{progress('Checking device compatibility…');await ai.load(progress);notice('The local model is ready. Course text stays on this device.');const b=document.querySelector('[data-action=load-ai]');if(b)b.textContent='AI is ready';}),
  'remove-model':()=>aiAction(async()=>{await ai.removeModel();notice('The model was unloaded and its cached files were removed.');const b=document.querySelector('[data-action=load-ai]');if(b)b.textContent='Load free AI model';}),
  'draft-one':generateOne,'use-assignment-slos':useAssignmentSlos,
  'choose-provided':()=>{state.sloMode='provided';notice('');renderOutcomes();},
  'choose-create':()=>{state.sloMode='create';notice('');renderOutcomes();},
  'add-provided':addProvided,
  'align-all':()=>aiAction(()=>alignSet(state.outcomes.map((_,i)=>i))),
  'align-one':i=>aiAction(()=>alignSet([i])),
  'delete-outcome':i=>{state.outcomes.splice(i,1);state.assignments=[];state.reviewed=false;renderOutcomes();},
  'rewrite-one':i=>aiAction(async()=>{await ensureAI();const draft=await ai.draftOutcome(state.course,state.outcomes[i].sentence,state.outcomes.filter((_,j)=>j!==i),state.outcomes.length,progress);state.outcomes[i]=draft;state.assignments=[];state.reviewed=false;dirty=true;renderOutcomes();notice('SLO rewritten and automatically aligned. Review the links and Bloom’s level.');}),
  'back-welcome':()=>show('welcome'),'back-course':()=>show('course'),'back-outcomes':()=>show('outcomes'),
  'to-assignments':()=>{requireOutcomes();show(state.goal==='slos'?'report':'assignments');},'generate-assignments':generateAssignments,
  'back-results':()=>show(state.goal==='slos'?'outcomes':'assignments'),'to-report':()=>{if(state.goal==='assignments'){if(!state.assignments.length)throw new Error('Create an assignment before exporting.');}else requireOutcomes();show('report');},'edit-assignment':editAssignment,
  copy:async()=>{await navigator.clipboard.writeText(blocksText(reportBlocks(state)));notice('The complete report was copied to your clipboard.');},
  pdf:()=>{window.print();},docx:async()=>{await exportDocx(state);notice('DOCX download prepared.');},html:()=>{exportHtml(state);notice('HTML download prepared. Open it in any browser.');},
};
document.addEventListener('click',e=>{const b=e.target.closest('[data-action]');if(b&&!busy)action(()=>actions[b.dataset.action]?.(Number(b.dataset.index)));});
document.addEventListener('input',e=>{if(e.target.closest('#course-panel'))dirty=true;if(e.target.id==='provided-slos'){state.sloInput=e.target.value;dirty=true;}if(e.target.closest('[data-outcome]'))updateOutcome(e.target);if(e.target.dataset.notes!==undefined){state.assignments[Number(e.target.dataset.notes)].notes=e.target.value;state.reviewed=false;dirty=true;}});
document.addEventListener('change',e=>{if(e.target.name==='assignment-slo')state.assignmentSloIndices=[...document.querySelectorAll('[name=assignment-slo]:checked')].map(el=>Number(el.value));if(e.target.name==='assignment-objective')state.assignmentObjectiveIds=[...document.querySelectorAll('[name=assignment-objective]:checked')].map(el=>Number(el.value));if(e.target.id==='reviewed'){state.reviewed=e.target.checked;$('report-content').innerHTML=blocksHTML(reportBlocks(state));}if(e.target.closest('[data-outcome]')){updateOutcome(e.target);if(e.target.dataset.field==='sentence'){const i=Number(e.target.closest('[data-outcome]').dataset.outcome);if(state.outcomes[i].sentence.trim()&&state.outcomes[i].alignmentStatus==='stale')aiAction(()=>alignSet([i]));}}if(e.target.closest('#assignments-panel')&&(['knowledge','duration','activity-count','resilient'].includes(e.target.id)||e.target.name==='modality')){state.settings={modalities:[...document.querySelectorAll('[name=modality]:checked')].map(x=>x.value),knowledge:$('knowledge').value,duration:$('duration').value,count:1,resilient:$('resilient').checked};if(state.assignments.length)notice('Settings changed. Existing assignments keep their original settings until you regenerate.');}});
document.querySelectorAll('.step').forEach(b=>b.onclick=()=>action(()=>{if(busy)return;if(state.step==='course'&&b.dataset.step!=='course')saveCourse();if(['assignments','report'].includes(b.dataset.step))requireOutcomes();show(b.dataset.step);}));
$('continue').onclick=()=>action(()=>{if(state.goal==='assignments')providedOutcomes($('existing').value);saveCourse();notice('');if(state.goal==='assignments')useAssignmentSlos();else show('outcomes');});
$('parse').onclick=()=>action(()=>applyParsed($('raw').value));
$('file').onchange=()=>action(async()=>{try{await importFile($('file').files[0]);}finally{$('file').value='';$('import-status').textContent='Import finished. Check the message and review your course fields.';}});
$('example').onclick=async()=>{if(dirty&&!await confirmAction('Replace this workspace with an example? Export any work you want to keep first.'))return;ai.stop();state.course=null;state.assignmentSloIndices=[];state.assignmentObjectiveIds=[];state.outcomes=[];state.assignments=[];state.reviewed=false;state.sloInput='';state.sloMode=null;$('title').value='Introduction to Environmental Science';$('description').value='An introductory exploration of ecosystem interactions, environmental evidence, and sustainable resource use. Students interpret accessible datasets and compare responses to local environmental challenges.';$('objectives').value='Explain interactions among organisms and their environment.\nAnalyze environmental data to assess human impacts on ecosystems.\nEvaluate strategies for sustainable resource use using scientific evidence.';$('existing').value=state.goal==='assignments'?'Analyze environmental data using two relevant observations.\nEvaluate sustainable resource strategies using scientific evidence.':'';dirty=true;notice(state.goal==='assignments'?'Example course and SLOs loaded. Choose assignment options to continue.':'Example course loaded. Edit it or continue to generate outcomes.');};
$('clear').onclick=async()=>{if(!await confirmAction('Clear all course text and drafts from this workspace? Downloaded files will remain on your device.'))return;ai.stop();importEpoch++;importWorker?.terminate();pdfTask?.destroy();state.course=null;state.assignmentSloIndices=[];state.assignmentObjectiveIds=[];state.outcomes=[];state.assignments=[];state.reviewed=false;state.sloInput='';state.sloMode=null;for(const k of ['title','description','objectives','existing','raw'])$(k).value='';dirty=false;setBusy(false);for(const k of ['outcomes','assignments','report'])$(k+'-panel').replaceChildren();$('import-status').textContent='';document.querySelectorAll('#course-panel details').forEach(d=>d.open=false);show('course');};
$('about-link').onclick=e=>{e.preventDefault();$('about').showModal();};$('close-about').onclick=()=>$('about').close();
window.addEventListener('beforeunload',e=>{if(dirty){e.preventDefault();e.returnValue='';}});
window.addEventListener('pagehide',()=>ai.stop());
// Restore no form values when a browser returns this document from its back/forward cache.
window.addEventListener('pageshow',e=>{if(e.persisted)location.reload();});
document.querySelectorAll('input,textarea').forEach(el=>{if(el.type!=='file')el.setAttribute('autocomplete','off');});

function updateGoal(goal){
  state.goal=goal;$('course-slos').hidden=goal!=='assignments';$('existing').required=goal==='assignments';
  $('creation-label').textContent={slos:'SLOs',assignments:'Assignments'}[goal];
  $('continue').textContent=goal==='assignments'?'Choose assignment options →':'Continue to SLOs →';
}
document.querySelectorAll('[data-goal]').forEach(b=>b.onclick=()=>{if(busy)return;updateGoal(b.dataset.goal);show('course');});
updateGoal('assignments');show('course');
